# Generated by Django 5.0.13 on 2025-12-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0002_application_joboffer_resumetemplate_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='match_score',
            field=models.IntegerField(blank=True, help_text="AI-generated score of how well the user's profile matches the offer.", null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='missing_skills',
            field=models.TextField(blank=True, help_text='AI-identified skills that the user is missing for this role.', null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the job offer.', null=True),
        ),
    ]
